<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Viernes_imgCheck</name>
   <tag></tag>
   <elementGuidId>8735f8ab-fc8f-4812-bd3a-db291606a134</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-md-1.col-lg-1.col-2.text-right.underDecoration > img.imgCheck</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='unchecked']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.col-md-1 > .imgCheck >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9f266563-1b08-485d-9bb4-62f578ee63c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./../../../assets/svg/checkout/icono-unchecked.svg</value>
      <webElementGuid>ade28629-83d7-4d7f-8c5c-75b6fb07393f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>c7622929-5407-4c38-a014-ae6006ade5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imgCheck</value>
      <webElementGuid>e1eb64e8-6314-419e-8b5f-c439736bafff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/cx-storefront[@class=&quot;MultiStepCheckoutSummaryPageTemplate stop-navigating&quot;]/main[@class=&quot;mouse-focus&quot;]/cx-page-layout[@class=&quot;MultiStepCheckoutSummaryPageTemplate&quot;]/cx-page-slot[@class=&quot;BodyContent has-components&quot;]/app-custom-delivery-mode[1]/div[3]/app-delivery-method-sheduling[1]/div[2]/div[1]/div[@class=&quot;tarjeta&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-md-1 col-lg-1 col-2 text-right underDecoration&quot;]/img[@class=&quot;imgCheck&quot;]</value>
      <webElementGuid>893dd845-1152-40a3-b6cc-e60b2f5a2be1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='unchecked']</value>
      <webElementGuid>fd6617b2-0f94-4d0b-9312-9b8941b1a6d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>bc82c62f-1158-4e33-b34c-e5c55a44168c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './../../../assets/svg/checkout/icono-unchecked.svg' and @alt = 'unchecked']</value>
      <webElementGuid>9934d613-9d6b-4336-927e-2afb727968ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
