<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Efectivo</name>
   <tag></tag>
   <elementGuidId>2c04b5c5-af8f-4f60-ace4-21fd9b6b08ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mobile-align</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Efectivo o tarjeta'])[1]/following::div[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Efectivo$/ >> nth=4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4dd2d31a-282f-464d-b43c-683a65338023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobile-align</value>
      <webElementGuid>16d97417-9fba-40e3-822a-13fe1781b578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Efectivo</value>
      <webElementGuid>bcd79689-5d23-431e-adc0-91aa92f374a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/cx-storefront[@class=&quot;MultiStepCheckoutSummaryPageTemplate stop-navigating&quot;]/main[@class=&quot;mouse-focus&quot;]/cx-page-layout[@class=&quot;MultiStepCheckoutSummaryPageTemplate&quot;]/cx-page-slot[@class=&quot;BodyContent has-components&quot;]/app-custom-payment-mode-component[1]/div[@class=&quot;main-payment&quot;]/div[@class=&quot;row custom-payment-row&quot;]/div[@class=&quot;col-12 order-4 order-md-4 p-2 c-pt-0&quot;]/div[@class=&quot;row custom-row&quot;]/div[@class=&quot;col-12 col-sm-6 custom-col&quot;]/div[1]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body card-item mobile-card-body&quot;]/div[@class=&quot;mobile-align&quot;]</value>
      <webElementGuid>31347e00-a795-4471-a33f-eb54dda33e4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Efectivo o tarjeta'])[1]/following::div[7]</value>
      <webElementGuid>a17d0ffb-77fc-4fe5-83d9-1de387a78016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Al recibir tu Pedido'])[1]/following::div[7]</value>
      <webElementGuid>aa1d615e-983b-49b0-833c-75269280c21d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tarjeta de crédito o débito'])[2]/preceding::div[1]</value>
      <webElementGuid>4b05a6c0-261d-42e1-ada8-07beededbd5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/div/div/div/div</value>
      <webElementGuid>434e4ba2-655e-4142-bfd5-25acff63b124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Efectivo' or . = 'Efectivo')]</value>
      <webElementGuid>62315fb9-bc6b-4c18-a9fc-27f187012ddc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
