<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Total</name>
   <tag></tag>
   <elementGuidId>74c0d558-a409-43b6-8f25-79e4b5f9cd42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h3[@class='textBoldGrey']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.textBoldGrey</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Total&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>7be2da5f-10e7-42cb-b4bd-f7a6c03b48c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textBoldGrey</value>
      <webElementGuid>a6a6f6fa-64a7-4edb-893d-ca4d5fc7018c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Total</value>
      <webElementGuid>96c42f49-c4a9-41d6-b99d-bb2e36428d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/cx-storefront[@class=&quot;MultiStepCheckoutSummaryPageTemplate stop-navigating&quot;]/main[@class=&quot;mouse-focus&quot;]/cx-page-layout[@class=&quot;MultiStepCheckoutSummaryPageTemplate&quot;]/cx-page-slot[@class=&quot;SideContent has-components&quot;]/app-order-summary[1]/div[@class=&quot;row orderSumary custom-orderSummary-fixed&quot;]/div[@class=&quot;container custom-container-fixed&quot;]/div[@class=&quot;row badgeSummary&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-5&quot;]/h3[@class=&quot;textBoldGrey&quot;]</value>
      <webElementGuid>ceb43b63-972d-48a6-adf1-e3c4ab7d209d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GRATIS'])[1]/following::h3[1]</value>
      <webElementGuid>7b00f4d0-3c78-4f47-b5ee-c6b0cb1659f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Costo de envío'])[1]/following::h3[1]</value>
      <webElementGuid>81cd4822-852c-4d81-bacd-d017d57f9a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$304.00 MXN'])[1]/preceding::h3[1]</value>
      <webElementGuid>749f4efb-da47-46a0-b0dd-3b71389968e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compras seguras, protegidas por'])[1]/preceding::h3[2]</value>
      <webElementGuid>9374d600-1550-41ac-91d5-75184b643899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Total']/parent::*</value>
      <webElementGuid>c918bc0d-f300-4240-91e1-2d3c7faa39c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/h3</value>
      <webElementGuid>adc5bbe8-95ae-4b21-9c94-d45d155ce2ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Total' or . = 'Total')]</value>
      <webElementGuid>88da8452-1fa3-45f2-a482-c014d7f21e09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
