<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Subtotal (1 producto)</name>
   <tag></tag>
   <elementGuidId>6476489f-16be-4239-bbbc-f50707c838d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//h4[@class=&quot;textLightGrey&quot;])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4.textLightGrey</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Subtotal (1 producto)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>821096d8-3f6c-487a-a53e-bdcbccd9b699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textLightGrey</value>
      <webElementGuid>d0d1a4e2-2d8f-477d-9cbe-c0b5cdfd7a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subtotal (1 producto)</value>
      <webElementGuid>13ebfa19-4b72-49c0-a6db-fb30ba835f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/cx-storefront[@class=&quot;MultiStepCheckoutSummaryPageTemplate stop-navigating&quot;]/main[@class=&quot;mouse-focus&quot;]/cx-page-layout[@class=&quot;MultiStepCheckoutSummaryPageTemplate&quot;]/cx-page-slot[@class=&quot;SideContent has-components&quot;]/app-order-summary[1]/div[@class=&quot;row orderSumary custom-orderSummary-fixed&quot;]/div[@class=&quot;container custom-container-fixed&quot;]/div[@class=&quot;row badgeSummary&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row mb-1&quot;]/div[@class=&quot;col-md-6&quot;]/h4[@class=&quot;textLightGrey&quot;]</value>
      <webElementGuid>31be6ec9-3131-41d4-aee7-f1bd83aab976</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resumen de compra'])[1]/following::h4[1]</value>
      <webElementGuid>a8779417-80dd-4f9f-8211-578ad245a290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nueva dirección'])[1]/following::h4[2]</value>
      <webElementGuid>08b45c37-2d60-4e42-814b-bec307f1cace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$436.00 MXN'])[1]/preceding::h4[1]</value>
      <webElementGuid>cc50172d-13f5-4d0f-836b-3b0a7c4c5859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Subtotal']/parent::*</value>
      <webElementGuid>72464c46-6879-4a64-a1f7-a118622bd2dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/h4</value>
      <webElementGuid>023e7d21-1dac-46bb-a59f-741fbd22e30b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Subtotal (1 producto)' or . = 'Subtotal (1 producto)')]</value>
      <webElementGuid>e06432a7-d19d-4cdc-90e6-9a69c971174d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
