<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cantidad</name>
   <tag></tag>
   <elementGuidId>45f788ed-3b53-4341-ac8c-982e8a7570df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'Cantidad')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-3.col-lg-3.col-auto.tapText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Cantidad&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fd99d42a-0366-464e-bbc5-1121acca13de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-3 col-lg-3 col-auto tapText</value>
      <webElementGuid>f59dd4a8-b356-4f3b-889f-c5f3eac7d4e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cantidad</value>
      <webElementGuid>66dc9759-64ab-493e-9e2f-2cb17c36b4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;header-scroll-hide&quot;]/app-root[1]/cx-storefront[@class=&quot;ProductDetailsPageTemplate stop-navigating&quot;]/main[@class=&quot;mouse-focus&quot;]/cx-page-layout[@class=&quot;ProductDetailsPageTemplate&quot;]/cx-page-slot[@class=&quot;Summary-Desk-Right has-components&quot;]/app-product-add-to-cart[1]/div[@class=&quot;row formQuantity divider-b&quot;]/div[@class=&quot;col-md-3 col-lg-3 col-auto tapText&quot;]</value>
      <webElementGuid>d83b2682-f0d3-4b6a-8e4b-74328c8d14a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consulta disponibilidad en sucursales'])[1]/following::div[2]</value>
      <webElementGuid>a91e68fe-056a-4f2f-8d5f-fcf934ef5aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consulta Términos y Condiciones.'])[1]/following::div[10]</value>
      <webElementGuid>839a610c-2a77-4e5c-bd10-3762e77257ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agregar al carrito'])[1]/preceding::div[5]</value>
      <webElementGuid>44de8a42-22ed-42fa-acf6-75cde2eedad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprar ahora'])[1]/preceding::div[6]</value>
      <webElementGuid>977058a3-cea7-4842-b853-39ca6c63c2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cantidad']/parent::*</value>
      <webElementGuid>165e7d31-d6b0-44e7-b025-01c737fc75d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-product-add-to-cart/div/div</value>
      <webElementGuid>1fbe59dc-0678-452f-9554-2e6ed80e9ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Cantidad' or . = 'Cantidad')]</value>
      <webElementGuid>44943259-0419-456b-98c5-81991ee82c32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
