<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>1dcf1958-47e1-4513-8f20-dc26352c12b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//cx-media[@class='mini-image is-initialized']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Silka Medic Defensa Desodorante en Aerosol para Pies Antitranspirante Antibacterial&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0bfc6125-b2d4-4918-940f-910f6e971967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://hfprod.farmaciasanpablo.com.mx/sys-master-azureproductimages/hc5/hfc/34791644561438/Fsp100Wx100H_Fsp800Wx800H_70006591_1_1hrosevth.jpg</value>
      <webElementGuid>351c202c-d71b-4931-ab07-bcecadaf173f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://hfprod.farmaciasanpablo.com.mx/sys-master-azureproductimages/hc5/hfc/34791644561438/Fsp100Wx100H_Fsp800Wx800H_70006591_1_1hrosevth.jpg 96w</value>
      <webElementGuid>27e0f782-0a9e-453a-850a-6ce1e66ada73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Silka Medic Defensa Desodorante en Aerosol para Pies Antitranspirante Antibacterial</value>
      <webElementGuid>ae36b171-72cc-446b-a3ad-c6697f4fe31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;header-scroll-hide&quot;]/app-root[1]/cx-storefront[@class=&quot;ProductDetailsPageTemplate stop-navigating&quot;]/main[@class=&quot;mouse-focus&quot;]/cx-page-layout[@class=&quot;ProductDetailsPageTemplate&quot;]/cx-page-slot[@class=&quot;Summary-Desk-Left has-components&quot;]/app-product-images[1]/app-cx-carosuel-custom[1]/div[@class=&quot;row justify-content-center rowThumnails&quot;]/cx-media[@class=&quot;mini-image is-initialized&quot;]/img[1]</value>
      <webElementGuid>96088e5b-c310-445f-b1a6-26b03d710e54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Silka Medic Defensa Desodorante en Aerosol para Pies Antitranspirante Antibacterial'])[3]</value>
      <webElementGuid>df39b0e6-661b-4f7e-a9fd-14bd3b7441b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cx-media[2]/img</value>
      <webElementGuid>0bc4d640-e59c-4af5-914f-8c5b208964d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://hfprod.farmaciasanpablo.com.mx/sys-master-azureproductimages/hc5/hfc/34791644561438/Fsp100Wx100H_Fsp800Wx800H_70006591_1_1hrosevth.jpg' and @alt = 'Silka Medic Defensa Desodorante en Aerosol para Pies Antitranspirante Antibacterial']</value>
      <webElementGuid>ed1bf12b-84ba-442e-afe2-7fe6b40afd4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
