<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Aerosoles</name>
   <tag></tag>
   <elementGuidId>dd119491-f33b-4b00-833b-5118156d79e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subcategory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='subcategory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Aerosoles&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>199da598-360d-4135-b2c6-bf2f5657ee25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subcategory</value>
      <webElementGuid>a9ce63a7-302e-46d3-b5d2-bad31412b855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>subcategory</value>
      <webElementGuid>78e2cbc5-6fd7-4e7a-b89a-409a570877ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/medicamentos/antimicoticos/aerosoles/c/060010001</value>
      <webElementGuid>14edc646-3a3a-46a3-a1d9-1f1086c91d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Aerosoles </value>
      <webElementGuid>fa0b9bcc-4970-4b1e-9557-c9fb4d2cd4c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub-Medicamentos&quot;)/div[@id=&quot;subcontent&quot;]/div[@class=&quot;subcategories&quot;]/div[@class=&quot;card&quot;]/a[@id=&quot;subcategory&quot;]</value>
      <webElementGuid>44873f9d-7cad-4085-ba2f-fa070880955f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='subcategory']</value>
      <webElementGuid>34c0d148-b695-4e40-bd1c-8b8de66bf70e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subcontent']/div/div/a</value>
      <webElementGuid>7557b306-bf88-4aa7-a15e-afe1271096fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Aerosoles')]</value>
      <webElementGuid>618762ff-abfa-43ff-a271-77b144815e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Antimicóticos'])[1]/following::a[1]</value>
      <webElementGuid>6e3dd93b-1f2a-46d2-a3b5-c07ce1c13f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medicamentos'])[2]/following::a[2]</value>
      <webElementGuid>9717983a-27be-46ed-9883-571de273abf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cremas, pomadas y ungüentos'])[1]/preceding::a[1]</value>
      <webElementGuid>3e4298ed-b571-49e5-8032-67caf7b7588d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Geles'])[1]/preceding::a[2]</value>
      <webElementGuid>6705c0b4-bd05-47ff-b6c8-51f37849f6ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aerosoles']/parent::*</value>
      <webElementGuid>7c757536-b1b0-4f3a-a842-522b1c45a091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/medicamentos/antimicoticos/aerosoles/c/060010001')]</value>
      <webElementGuid>efec53ca-2644-429c-af03-cfd281e64474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>82756b2c-6e39-4a08-b379-e926700aea72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'subcategory' and @href = '/medicamentos/antimicoticos/aerosoles/c/060010001' and (text() = ' Aerosoles ' or . = ' Aerosoles ')]</value>
      <webElementGuid>ff23213e-b5eb-443f-8b26-300acda3d716</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
