<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Antimicticos</name>
   <tag></tag>
   <elementGuidId>ce4cf1d3-17fd-4436-a2dc-d371948c067c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card > p > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subcontent']/div/div/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Antimicóticos&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>33e6244b-7329-48a0-ab43-ee688dfb4725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/medicamentos/antimicoticos/c/06001</value>
      <webElementGuid>9451fb48-c99b-4272-8dda-2dcbe9cd669b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Antimicóticos</value>
      <webElementGuid>c6d48938-3cee-4d10-bada-33657d29a800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub-Medicamentos&quot;)/div[@id=&quot;subcontent&quot;]/div[@class=&quot;subcategories&quot;]/div[@class=&quot;card&quot;]/p[1]/a[1]</value>
      <webElementGuid>2f89a67a-b110-4a95-9ae0-79881279127e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subcontent']/div/div/p/a</value>
      <webElementGuid>3c936a4b-3b73-44e7-8e66-6276a0a2698b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Antimicóticos')]</value>
      <webElementGuid>d19ae892-48a9-4c9f-b23b-60b59ea096b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medicamentos'])[2]/following::a[1]</value>
      <webElementGuid>35253a7f-df4f-43e6-946f-0a8bf4e55a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medicamentos'])[1]/following::a[2]</value>
      <webElementGuid>d76c1214-31d7-4b77-8fc6-15551e644c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aerosoles'])[1]/preceding::a[1]</value>
      <webElementGuid>117d37ff-25c9-45da-94d4-900c84413bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cremas, pomadas y ungüentos'])[1]/preceding::a[2]</value>
      <webElementGuid>ed537702-5319-4356-981b-60fad24b88c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Antimicóticos']/parent::*</value>
      <webElementGuid>e4c414cf-fb1e-4822-95f2-8f2d1ce48ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/medicamentos/antimicoticos/c/06001')]</value>
      <webElementGuid>2819ba6c-7d29-4d7b-8343-2dd83c5d5fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p/a</value>
      <webElementGuid>aa4d49e7-e029-4bc2-a3f3-2c31347c2b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/medicamentos/antimicoticos/c/06001' and (text() = 'Antimicóticos' or . = 'Antimicóticos')]</value>
      <webElementGuid>617a7c32-edee-43a6-8f15-872d22d41f6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
