<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Medicamentos</name>
   <tag></tag>
   <elementGuidId>e73810ed-93bb-412a-8cdd-46d214f88882</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.medicamentos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sub-Medicamentos']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Medicamentos&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>01cb38e4-bec3-4bda-a953-af5c7531cb53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>medicamentos</value>
      <webElementGuid>ace3fd76-cfa1-434f-94ef-4b7dd83dfbe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/medicamentos/c/06</value>
      <webElementGuid>105f3218-4bd9-46fa-aeb8-3e4ae874407f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Medicamentos</value>
      <webElementGuid>ddd03435-3da1-4f57-a5ab-6f7a0751024d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub-Medicamentos&quot;)/div[@class=&quot;title&quot;]/a[@class=&quot;medicamentos&quot;]</value>
      <webElementGuid>e921a6ba-e479-41f3-bcf5-3aa3cae1ce01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sub-Medicamentos']/div/a</value>
      <webElementGuid>0d5746aa-0917-4c7c-9b55-42e5d6f5b495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Medicamentos')])[2]</value>
      <webElementGuid>d0aecec4-8f68-46f3-9d34-77b62e00c8a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medicamentos'])[1]/following::a[1]</value>
      <webElementGuid>7059c983-8b0b-47fc-89ee-7cfbff2abbdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categorías'])[1]/following::a[2]</value>
      <webElementGuid>99473d02-9c85-4b6b-b700-11b7ea4953ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Antimicóticos'])[1]/preceding::a[1]</value>
      <webElementGuid>4c5701a5-0441-468e-acf6-011268ab118b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aerosoles'])[1]/preceding::a[2]</value>
      <webElementGuid>ddd29bd6-dd89-4d22-9ab7-c3719417c3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/medicamentos/c/06')]</value>
      <webElementGuid>32dfce92-2da6-4727-a175-443380d209f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div[2]/div/a</value>
      <webElementGuid>584657b9-aa1a-4abf-a7aa-6d08a34fc467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/medicamentos/c/06' and (text() = 'Medicamentos' or . = 'Medicamentos')]</value>
      <webElementGuid>cd1a6cf6-53ec-4e45-bbad-45964b8c5126</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
