<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_concat( i class, , fas fa-chevron-right_898612</name>
   <tag></tag>
   <elementGuidId>f802a1cc-a021-447b-80fa-37771293759e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sliderGrid-home-estacionOfertas-secundarias-banner01</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='sliderGrid-home-estacionOfertas-secundarias-banner01']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Estación de Ofertas&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>174176a6-9c87-4d08-bfe7-b0d7e5b2e2a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets1.farmaciasanpablo.com.mx/landings/HardSell/2406-EstaciondeOfertas/Sem03/CintilloGrid-EstaciondeOfertas24-sem03-m-v1@2x.jpg</value>
      <webElementGuid>ec23ad03-b569-4f02-accc-85d60faf6978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Estación de Ofertas</value>
      <webElementGuid>ae5a9657-f99e-4379-ad61-12f6d05fdc90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sliderGrid-home-estacionOfertas-secundarias-banner01</value>
      <webElementGuid>4b4b7c39-9dfa-4e67-b3b8-b1c819fd9468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sliderGrid-home-estacionOfertas-secundarias-banner01&quot;)</value>
      <webElementGuid>39e3300e-021a-476b-a3e2-3fa8cb0e0473</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='sliderGrid-home-estacionOfertas-secundarias-banner01']</value>
      <webElementGuid>59049024-5623-4344-a7ec-3cba0c798c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Estación de Ofertas']</value>
      <webElementGuid>dcd42f84-6ec8-4fba-9a87-28890a871abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/picture/img</value>
      <webElementGuid>9ef05b04-abc0-4c9f-b31d-5fd6c9dad245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets1.farmaciasanpablo.com.mx/landings/HardSell/2406-EstaciondeOfertas/Sem03/CintilloGrid-EstaciondeOfertas24-sem03-m-v1@2x.jpg' and @alt = 'Estación de Ofertas' and @id = 'sliderGrid-home-estacionOfertas-secundarias-banner01']</value>
      <webElementGuid>a24f2c3a-8e46-4f55-809e-871456ead587</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
