<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Atencin a clientes_searchBoxId</name>
   <tag></tag>
   <elementGuidId>4ed0a5b7-de2b-4688-a81b-4a1e498b324a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchBoxId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchBoxId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;¿Qué estás buscando?&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1dacc005-84d4-4202-b6db-423aae845383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchBoxId</value>
      <webElementGuid>ea1f9127-d7ef-4ba8-b15c-fb7ae066771c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>d518a5c9-2bd1-4bf7-8919-b76ed26a0b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>¿Qué estás buscando?</value>
      <webElementGuid>e9207d1b-d53a-465b-99c0-11d920856dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchBoxId&quot;)</value>
      <webElementGuid>4e016457-d15d-4582-9b70-716ea3ae78ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchBoxId']</value>
      <webElementGuid>fc5bb9b6-9751-4a6f-bc33-4b9d9fa4b394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='cx-header']/cx-page-layout/cx-page-slot[5]/app-custom-searchbox/label/input</value>
      <webElementGuid>e2da8f85-cfd9-4f84-bfcb-a8bb1f551343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e264135c-1618-4eb6-9696-74b986495fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchBoxId' and @placeholder = '¿Qué estás buscando?']</value>
      <webElementGuid>40fbc9d6-73f8-403e-84e5-21d675353b60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
