<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Enviar_a_Cdiga_Postal_14000_(after login postal code)</name>
   <tag></tag>
   <elementGuidId>44d7ee64-1240-4e88-bf0d-eab4fb59b2c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='cx-header']/cx-page-layout/cx-page-slot[6]/app-custom-login/div[2]/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.cp-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Enviar a Código Postal: 14000&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>97b6093e-ac74-4d5a-b409-f72dc22b06b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cp-text</value>
      <webElementGuid>aaad82d6-a27a-4c76-866d-90a223815782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Enviar a Código Postal: 14000</value>
      <webElementGuid>e30efe85-101b-44b7-a925-1d7b1aa14174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cx-header&quot;)/cx-page-layout[@class=&quot;header&quot;]/cx-page-slot[@class=&quot;SiteLogin has-components&quot;]/app-custom-login[1]/div[@class=&quot;headerFixed&quot;]/div[@class=&quot;send-to cp-complete&quot;]/div[1]/p[@class=&quot;cp-text&quot;]</value>
      <webElementGuid>7b4baa66-66a5-4055-a3dd-e06040a94fc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='cx-header']/cx-page-layout/cx-page-slot[6]/app-custom-login/div[2]/div/div/p</value>
      <webElementGuid>c15e9731-3f9a-44ac-aaa5-4d752d99461e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Club salud'])[2]/following::p[1]</value>
      <webElementGuid>2c932385-93fa-499e-8767-3c004a097d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preguntas frecuentes'])[1]/following::p[1]</value>
      <webElementGuid>80c0626c-5ea9-4f40-bdc2-232d30e07c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carrito'])[1]/preceding::p[1]</value>
      <webElementGuid>66a9e5a5-87a1-42df-b500-1cc341ab38e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tienes 3 artículos en tu carrito'])[1]/preceding::p[1]</value>
      <webElementGuid>c925d28d-89ff-40b5-8bb1-eadf40114d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enviar a Código Postal:']/parent::*</value>
      <webElementGuid>f77524ff-ad73-4c85-954d-78ae20be2fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/p</value>
      <webElementGuid>3d595f59-94e7-4843-a4ad-f1adf66fd04f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = ' Enviar a Código Postal: 14000' or . = ' Enviar a Código Postal: 14000')]</value>
      <webElementGuid>4249a178-e533-4cf0-aed2-9afef470128d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
