<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Logo_HP</name>
   <tag></tag>
   <elementGuidId>80b13691-1025-4625-973b-f35d84d96806</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='cx-header']/cx-page-layout/cx-page-slot[4]/cx-banner/cx-generic-link/a/cx-media/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;FSP Logo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;FSP Logo&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3ffb91a7-6bfc-451c-a64c-7b87a984441a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://3230j5vu2h77l4hojbycpuf.blob.core.windows.net/sys-master-cmsimages/h41/h8b/8864185057310/logo.png</value>
      <webElementGuid>df5b5048-55d0-42af-8d15-eb7571958e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>FSP Logo</value>
      <webElementGuid>3375c656-2fe3-4034-8a1c-2603ec5f7736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cx-header&quot;)/cx-page-layout[@class=&quot;header&quot;]/cx-page-slot[@class=&quot;SiteLogo has-components&quot;]/cx-banner[@class=&quot;logo-fsp&quot;]/cx-generic-link[1]/a[1]/cx-media[@class=&quot;is-initialized&quot;]/img[1]</value>
      <webElementGuid>1d97887b-778d-4b96-ae7a-b963d6e8e8c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='cx-header']/cx-page-layout/cx-page-slot[4]/cx-banner/cx-generic-link/a/cx-media/img</value>
      <webElementGuid>5c6e8c1c-f990-4c29-a373-6adb100c8408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='FSP Logo']</value>
      <webElementGuid>2ab5e4e7-442e-416e-8799-6d0985d7469c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>c198bb2d-92cd-405a-b161-d26b4378b9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://3230j5vu2h77l4hojbycpuf.blob.core.windows.net/sys-master-cmsimages/h41/h8b/8864185057310/logo.png' and @alt = 'FSP Logo']</value>
      <webElementGuid>623d4ce4-b425-4b8b-9ace-7edb3ebc8311</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
