<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Medicamentos_L1_category_HP</name>
   <tag></tag>
   <elementGuidId>4e582627-0bbe-41d2-824b-d24003732e4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='categories']/li/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.content-menu > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Medicamentos$/ >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0567816b-a9b9-4a85-aaa0-6ca561e49492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Medicamentos</value>
      <webElementGuid>a85f3f3d-36e5-4ae2-af55-2f4724f7373e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categories&quot;)/li[@class=&quot;content-menu&quot;]/div[1]</value>
      <webElementGuid>97d8ae7e-89dc-4d8f-8446-a0046bf475fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='categories']/li/div</value>
      <webElementGuid>d0053194-a9b2-4b23-93df-6cd44d0311e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categorías'])[1]/following::div[2]</value>
      <webElementGuid>c5c05334-003f-4290-b600-dc056ea81d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar Carrito'])[1]/following::div[2]</value>
      <webElementGuid>39501547-b1f8-47b4-a885-6abd3f67ef2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medicamentos'])[2]/preceding::div[1]</value>
      <webElementGuid>dd3b37d4-b6b6-4c7a-af10-2bb3137f7fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div</value>
      <webElementGuid>2a354c32-a18b-431c-9bf6-8b53aeb18292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Medicamentos' or . = 'Medicamentos')]</value>
      <webElementGuid>57adc84c-60bd-4145-a234-392328bdab32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
