<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>No_button_Popup_HP</name>
   <tag></tag>
   <elementGuidId>efa252d6-79ed-4c65-a3fa-9c108e223de4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pushengage-opt-in-1-close']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pushengage-opt-in-1-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#pushengage-opt-in-1-close</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7870aa6a-9995-45b8-a756-2a37dd59975b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pushengage-opt-in__safari-style__button__close</value>
      <webElementGuid>92af61ef-a47f-425b-89e5-8ad38affb18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pushengage-opt-in-1-close</value>
      <webElementGuid>b7fed23b-fdf3-4308-a5a0-438a15f4de67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          No
        </value>
      <webElementGuid>b7a3ee5d-dcf8-43dd-a1d1-2c36c46e9f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pushengage-opt-in-1-close&quot;)</value>
      <webElementGuid>ebb8058e-b7ef-45cf-bcca-e6b819ee1a1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pushengage-opt-in-1-close']</value>
      <webElementGuid>e4024968-358b-4527-b992-0ed5e806a46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pushengage-opt-in-1']/div[2]/div[2]</value>
      <webElementGuid>196a4135-8020-49fa-8289-999445f1fff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Deseas recibir ofertas de San Pablo Farmacia?'])[1]/following::div[3]</value>
      <webElementGuid>b1779c73-724f-43eb-a127-7911cbede1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PushEngage'])[1]/preceding::div[1]</value>
      <webElementGuid>1d0ae408-edea-41af-9fae-3a9cf5288b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[2]</value>
      <webElementGuid>723bd395-5a26-40fa-9d77-ffac7910d7f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'pushengage-opt-in-1-close' and (text() = '
          No
        ' or . = '
          No
        ')]</value>
      <webElementGuid>eeb45ca1-5ecf-49b2-b964-8a490ef27362</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
