<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SideBox_HP</name>
   <tag></tag>
   <elementGuidId>f802a1cc-a021-447b-80fa-37771293759e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='sidebox-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sliderGrid-home-estacionOfertas-secundarias-banner01</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Estación de Ofertas&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7b134b2c-3b08-4846-a90e-2c9c1f02cfe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets1.farmaciasanpablo.com.mx/landings/HardSell/2406-EstaciondeOfertas/Sem03/CintilloGrid-EstaciondeOfertas24-sem03-m-v1@2x.jpg</value>
      <webElementGuid>83a5f69b-8519-488c-9995-0431055d1e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Estación de Ofertas</value>
      <webElementGuid>3dcc23ef-1508-4c82-b43c-a2f9e09018ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sliderGrid-home-estacionOfertas-secundarias-banner01</value>
      <webElementGuid>ee8e7206-d001-4e92-968b-29e5e37c1372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sliderGrid-home-estacionOfertas-secundarias-banner01&quot;)</value>
      <webElementGuid>864f5af3-a764-4ff6-88da-059ccc65920b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='sliderGrid-home-estacionOfertas-secundarias-banner01']</value>
      <webElementGuid>0ee543f9-88c4-4618-bb3b-4acfd19357bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Estación de Ofertas']</value>
      <webElementGuid>d761b2f7-d20f-49f6-a5fe-a9725ff5b628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/picture/img</value>
      <webElementGuid>f3f5a343-9819-4444-a59f-4a2682474faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets1.farmaciasanpablo.com.mx/landings/HardSell/2406-EstaciondeOfertas/Sem03/CintilloGrid-EstaciondeOfertas24-sem03-m-v1@2x.jpg' and @alt = 'Estación de Ofertas' and @id = 'sliderGrid-home-estacionOfertas-secundarias-banner01']</value>
      <webElementGuid>2de598e8-071a-4bff-a0d5-b7db0edd061f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
