<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProductImage_pdp</name>
   <tag></tag>
   <elementGuidId>fe6de9cd-df19-4846-9826-0193213f8e70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div//img[@class='imgPDP']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
