<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Precio</name>
   <tag></tag>
   <elementGuidId>7130700b-4128-4e27-907f-335c9039ad4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(text(),' Precio ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Precio &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ce827437-f6f5-430d-b1a7-f2c81e3f6a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>fea1dc11-9de1-4db1-9c6c-e6b173171439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>498b9cfa-3094-486f-a353-b3cd8b0d9b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>6c1da1b5-47a0-4290-8c81-36215cb74428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Precio </value>
      <webElementGuid>2bcbe3ea-0dcf-43a2-b98c-96ad2480fcae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/cx-storefront[@class=&quot;ProductListPageTemplate stop-navigating&quot;]/main[@class=&quot;mouse-focus&quot;]/cx-page-layout[@class=&quot;ProductListPageTemplate&quot;]/cx-page-slot[@class=&quot;ProductLeftRefinements has-components&quot;]/cx-product-facet-navigation[1]/cx-facet-list[1]/section[@class=&quot;inner&quot;]/cx-facet[@class=&quot;expanded&quot;]/button[@class=&quot;heading&quot;]</value>
      <webElementGuid>00c0835e-263d-4098-a1ab-8639607246bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtrar'])[2]/following::button[2]</value>
      <webElementGuid>66c738d5-a113-4562-948b-9427995fc516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtrar'])[1]/following::button[2]</value>
      <webElementGuid>5816f9a4-f693-44e3-bf77-39c624234326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marca'])[1]/preceding::button[1]</value>
      <webElementGuid>dce34aca-74a6-4ecc-80a4-a91f782e63f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Segmento'])[1]/preceding::button[2]</value>
      <webElementGuid>e7808ff4-8a96-4c41-b596-57bf1997cd0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Precio']/parent::*</value>
      <webElementGuid>d21451f7-3a1c-45b2-b8e5-c3af978d7a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cx-facet/button</value>
      <webElementGuid>4adde7db-93ce-457e-9dbe-6e47477b88cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Precio ' or . = ' Precio ')]</value>
      <webElementGuid>a5301b91-bf4b-443f-aadb-333ab5049b33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
