<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>7e401c72-9bdb-49ca-854c-9fe33cc7835d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//cx-media[@class='imageItemList noneImage is-initialized'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>cx-media.imageItemList.noneImage.is-initialized > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>app-product-list-item >> internal:has-text=&quot;30% de Descuento Silka Medic Defensa Desodorante en Aero... 150 ML Lata $109.00 &quot;i >> internal:role=link >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>60c2c3d2-c38a-4777-84af-9ad3b3860d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://hfprod.farmaciasanpablo.com.mx/sys-master-azureproductimages/h54/h9d/34791643873310/Fsp275Wx275H_Fsp800Wx800H_70006591_1hrosevth.jpg</value>
      <webElementGuid>01abb9c5-cf5a-48eb-9515-b254c7fcd03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://hfprod.farmaciasanpablo.com.mx/sys-master-azureproductimages/h52/ha0/34791643938846/Fsp100Wx100H_Fsp800Wx800H_70006591_1hrosevth.jpg 96w, https://hfprod.farmaciasanpablo.com.mx/sys-master-azureproductimages/h54/h9d/34791643873310/Fsp275Wx275H_Fsp800Wx800H_70006591_1hrosevth.jpg 284w</value>
      <webElementGuid>ba5a1a72-fd7d-4c01-b2e9-cbed2b0e5434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;header-scroll-hide&quot;]/app-root[1]/cx-storefront[@class=&quot;ProductListPageTemplate stop-navigating&quot;]/main[@class=&quot;mouse-focus&quot;]/cx-page-layout[@class=&quot;ProductListPageTemplate&quot;]/cx-page-slot[@class=&quot;ProductListSlot has-components&quot;]/app-product-list[1]/div[2]/div[@class=&quot;row no-gutters justify-content-center&quot;]/div[@class=&quot;col-md-3 col-lg-3 col-sm-6 col-6&quot;]/app-product-list-item[1]/div[@class=&quot;shadow bg-white rounded cardItemCustom&quot;]/div[3]/a[@class=&quot;row m-0 justify-content-center imageAlert&quot;]/cx-media[@class=&quot;imageItemList noneImage is-initialized&quot;]/img[1]</value>
      <webElementGuid>8fb423e8-bc14-4087-9ee7-dd8cbe1a3b4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://hfprod.farmaciasanpablo.com.mx/sys-master-azureproductimages/h54/h9d/34791643873310/Fsp275Wx275H_Fsp800Wx800H_70006591_1hrosevth.jpg')]</value>
      <webElementGuid>13e2276d-4f06-4f10-b777-feb8a93700b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/cx-media/img</value>
      <webElementGuid>0435bc0d-12a9-4464-bbb4-9e567ebe1414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://hfprod.farmaciasanpablo.com.mx/sys-master-azureproductimages/h54/h9d/34791643873310/Fsp275Wx275H_Fsp800Wx800H_70006591_1hrosevth.jpg']</value>
      <webElementGuid>5115f44c-87ec-4fc3-a4d6-ba16a093f20e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
