<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Todas_las_Categoras</name>
   <tag></tag>
   <elementGuidId>dffee62e-a266-4c99-a6f5-e95cfd81eb77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar sesión'])[2]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.subTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Todas las Categorías&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>10a484d4-fcad-4891-a91b-5eb88cfb8cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>subTitle</value>
      <webElementGuid>6fc1dc65-daf9-418e-ba7a-c1fe7b2122ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-recent-on-screen2753664_2348</name>
      <type>Main</type>
      <value>226343</value>
      <webElementGuid>cd88be2f-20d2-4012-8c45-9cf496b98ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-first-on-screen2753664_2348</name>
      <type>Main</type>
      <value>226343</value>
      <webElementGuid>08348a2a-7fe2-41d2-8bfb-a55eaef545af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-total-visible-time2753664_2348</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>8ff8c658-cfd5-4d22-a0d4-3028b4f4fdf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-has-fired2753664_2348</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d35a583f-ffb1-4960-b9fa-70e923281246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Todas las Categorías</value>
      <webElementGuid>1692e09c-56f2-4327-a52e-bfb052f721c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/cx-storefront[@class=&quot;ProductListPageTemplate stop-navigating&quot;]/main[@class=&quot;mouse-focus&quot;]/cx-page-layout[@class=&quot;ProductListPageTemplate&quot;]/cx-page-slot[@class=&quot;ProductLeftRefinements has-components&quot;]/app-resultados-sub-header[1]/div[@class=&quot;subHeaderTitle&quot;]/span[@class=&quot;subTitle&quot;]</value>
      <webElementGuid>299abc4c-b893-4707-9e6f-405afc81e938</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar sesión'])[2]/following::span[1]</value>
      <webElementGuid>759d704c-c2a7-4a06-bc89-d3c85c2e1a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ofertas Clics de Bienestar'])[1]/following::span[1]</value>
      <webElementGuid>03aef644-31eb-47ed-a5ce-2e48cd28cae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(4 resultados)'])[1]/preceding::span[1]</value>
      <webElementGuid>7173f94d-868d-4646-82fd-421eee98b801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtrar'])[1]/preceding::span[2]</value>
      <webElementGuid>d1842d38-5684-4fbe-8d99-e4d1bd83614e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Todas las Categorías']/parent::*</value>
      <webElementGuid>2a1ca839-c698-4d0b-bc23-2174760062cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-resultados-sub-header/div/span</value>
      <webElementGuid>27d4ff1d-6944-4569-befc-8f2339ca8cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Todas las Categorías' or . = 'Todas las Categorías')]</value>
      <webElementGuid>83e24ad9-a506-49f3-a505-ea51144b5e55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
